### ISSUE TITLE
Uranium socket on tools not reducing user's maximum health

### ISSUE THREAD

**Issue by meeprdib** [Syrikal/Tetranomicon#19] opened 2024-01-07 03:57 UTC
Item with uranium socket has a tooltip that says it reduces the user's max HP by 4, but the effect is not applied.

Edit: Effect is inconsistent and only works sometimes.

**Comment by Syrikal** [comment] 2024-02-03 23:47
Closed as working as intended - the socket reduces max health and therefore prevents healing, but does not actually damage the player.

**Closed as completed** 2024-02-03 23:47 UTC
Labels: wontfix
